#!/bin/bash
# resolve-runner-targets.sh — Config resolution, merge, and cache generation
# for runner targets configuration.
#
# Source this file: . "${SCRIPT_DIR}/lib/resolve-runner-targets.sh"
#
# Depends on: validate.sh (for validate_runner_targets_file, validate_runner_name)
#
# Bash requirement: 4.3+ — `emit_runner_json()` uses `local -n` namerefs
# (added in Bash 4.3, Feb 2014). Callers must enforce this. The session-start
# hook in this plugin already gates on BASH_VERSINFO[0] >= 4 with a graceful
# skip; per-callsite consumers sourcing this lib directly should check
# `[ "${BASH_VERSINFO[0]}" -gt 4 ] || { [ "${BASH_VERSINFO[0]}" -eq 4 ] && [ "${BASH_VERSINFO[1]}" -ge 3 ]; }`
# before calling `emit_runner_json()` or `resolve_runner_targets()`.
#
# YAML parsing constraint: This parser handles only the canonical format
# generated by /ci:setup-runner-targets (2-space indent, block sequences only).
# Flow syntax ([a, b]), multi-line scalars (|, >), and tabs are NOT supported.
# If hand-edited YAML uses these features, the parser fails gracefully.
#
# Design choice: We intentionally avoid a yq dependency. The setup command
# generates canonical YAML, and the session-start hook reads a pre-rendered
# cache (not raw YAML). This parser is only invoked by the setup command and
# resolve_runner_targets(), both of which run outside the 3s hook budget.
# If a proper YAML parser is needed in the future, yq can be added as an
# optional dependency with graceful fallback to this parser.
#
# Delimiter limitation: The internal transport uses | between fields and ,
# between array items. Free-text values (best_for, avoid_for, notes) that
# contain literal commas or pipes will be incorrectly split. The setup command
# should avoid generating such values. If this becomes a real issue, switch
# the awk output to JSON Lines format.

# Resolve the global config path (XDG-compliant)
# Usage: rt_global_path
rt_global_path() {
  printf '%s' "${XDG_CONFIG_HOME:-$HOME/.config}/yellow-ci/runner-targets.yaml"
}

# Resolve the local (per-repo) config path
# Usage: rt_local_path
rt_local_path() {
  printf '%s' ".claude/yellow-ci-runner-targets.yaml"
}

# Resolve the cache directory (R38). WRITES go to a plugin-data location; this
# matches the Node SessionStart hook's newCacheDir() so the routing-summary the
# hook reads is produced at the same place. env-var resolution lives in this
# (non-exposure-linted) lib layer; Codex sets CLAUDE_PLUGIN_DATA for plugin-hook
# compat.
# Usage: rt_cache_dir
rt_cache_dir() {
  printf '%s' "${CLAUDE_PLUGIN_DATA:-${XDG_DATA_HOME:-$HOME/.local/share}/yellow-ci}"
}

# Legacy cache directory — READ-ONLY fallback target (R38). New writes never go
# here; the SessionStart hook and merged-config readers fall back to it only
# when the new location has no cache yet. Exception: stale-cache cleanup below
# also removes files here on config removal/invalidation, so the read-fallback
# doesn't keep resurfacing a deleted config's routing data indefinitely.
# Usage: rt_legacy_cache_dir
rt_legacy_cache_dir() {
  printf '%s' "${HOME}/.cache/yellow-ci"
}

# Atomically write content to a cache file (write to tmp, then rename).
# A partial write leaves the destination untouched. Warnings go to stderr;
# the caller is never failed — cache writes are best-effort.
# Usage: rt_atomic_write "$content" "$dest_path"
rt_atomic_write() {
  local content="$1" dest="$2"
  local tmp="${dest}.tmp.$$"
  if printf '%s' "$content" > "$tmp" 2>/dev/null; then
    mv "$tmp" "$dest" 2>/dev/null || {
      printf '[yellow-ci] Warning: Cache write failed for %s\n' "$(basename "$dest")" >&2
      rm -f "$tmp" 2>/dev/null
    }
  else
    printf '[yellow-ci] Warning: Cannot write tmp file %s\n' "$tmp" >&2
    # Disk full / permission failure may leave a zero-byte tmp; clean up.
    rm -f "$tmp" 2>/dev/null
  fi
}

# Build the merged runner-targets JSON document.
# Args:
#   $1 — name of the indexed array holding runner order (passed by nameref)
#   $2 — name of the associative array of pipe-delimited runner data (nameref)
#   $3 — rules_source path (empty string if no routing rules)
#   $4 — has_global (0|1)        $5 — has_local (0|1)
#   $6 — global_path             $7 — local_path
# Output: the JSON string on stdout.
emit_runner_json() {
  local -n _order="$1"
  local -n _runners="$2"
  local rules_source="$3" has_global="$4" has_local="$5"
  local global_path="$6" local_path="$7"

  local json='{"schema":1,"runner_targets":['
  local first=1
  local rname rdata _rname_unused rtype rmode selectors bf af nt sel_json bf_json af_json nt_json
  for rname in "${_order[@]}"; do
    rdata="${_runners[$rname]}"
    # Parse all 7 pipe-delimited fields in one read — replaces 6
    # printf|cut subshells per runner. _rname_unused absorbs field 1
    # (the runner name), which we already know from the loop variable.
    IFS='|' read -r _rname_unused rtype rmode selectors bf af nt <<< "$rdata"

    # Validate type/mode before JSON interpolation (prevents injection)
    if [ -n "$rtype" ] && ! validate_runner_type "$rtype"; then
      printf '[yellow-ci] Warning: Invalid runner type for %s: %s — skipping\n' "$rname" "$rtype" >&2
      continue
    fi
    if [ -n "$rmode" ] && ! validate_runner_mode "$rmode"; then
      printf '[yellow-ci] Warning: Invalid runner mode for %s: %s — skipping\n' "$rname" "$rmode" >&2
      continue
    fi

    [ "$first" -eq 1 ] && first=0 || json="${json},"

    # Build JSON arrays from comma-separated values
    sel_json=$(csv_to_json_array "$selectors")
    bf_json=$(csv_to_json_array "$bf")
    af_json=$(csv_to_json_array "$af")
    nt_json=$(csv_to_json_array "$nt")

    json="${json}{\"name\":\"${rname}\",\"type\":\"${rtype}\",\"mode\":\"${rmode}\""
    json="${json},\"preferred_selector\":${sel_json}"
    json="${json},\"best_for\":${bf_json}"
    json="${json},\"avoid_for\":${af_json}"
    json="${json},\"notes\":${nt_json}}"
  done
  json="${json}]"

  # Add routing rules
  if [ -n "$rules_source" ]; then
    json="${json},\"routing_rules\":["
    local rfirst=1 rule
    while IFS= read -r rule; do
      [ "$rfirst" -eq 1 ] && rfirst=0 || json="${json},"
      # Escape backslashes then double quotes for valid JSON. Bash
      # parameter expansion is in-process — replaces a sed subshell per
      # routing rule.
      rule="${rule//\\/\\\\}"
      rule="${rule//\"/\\\"}"
      json="${json}\"${rule}\""
    done < <(rt_extract_rules "$rules_source")
    json="${json}]"
  fi

  json="${json},"
  # Escape paths for safe JSON interpolation (may contain backslashes on WSL).
  # Bash parameter expansion — no subshell per emit.
  local esc_global="${global_path//\\/\\\\}"
  esc_global="${esc_global//\"/\\\"}"
  local esc_local="${local_path//\\/\\\\}"
  esc_local="${esc_local//\"/\\\"}"
  json="${json}\"_meta\":{\"global_path\":\"${esc_global}\",\"local_path\":\"${esc_local}\""
  json="${json},\"has_global\":${has_global},\"has_local\":${has_local}}}"

  printf '%s' "$json"
}

# Extract runner target blocks from a YAML file as JSON-like lines
# Each runner becomes: name|type|mode|selector1,selector2|best1,best2|avoid1,avoid2|note1,note2
# Usage: rt_extract_runners "$filepath"
# Output: one pipe-delimited line per runner target
rt_extract_runners() {
  local filepath="$1"

  if [ ! -f "$filepath" ]; then
    return 1
  fi

  awk '
  BEGIN { in_targets = 0; in_runner = 0; field = ""; name = ""; rtype = ""; mode = "" }
  # Detect runner_targets section
  /^runner_targets:/ { in_targets = 1; next }
  # Detect end of runner_targets section (new top-level key)
  in_targets && /^[a-z]/ { in_targets = 0; flush_runner() }
  # Detect new runner entry
  in_targets && /^[[:space:]]*-[[:space:]]+name:/ {
    flush_runner()
    in_runner = 1
    sub(/^[[:space:]]*-[[:space:]]+name:[[:space:]]*/, "")
    sub(/[[:space:]]*$/, "")
    name = $0
    rtype = ""; mode = ""
    split("", selectors); sel_count = 0
    split("", best_for); bf_count = 0
    split("", avoid_for); af_count = 0
    split("", notes); note_count = 0
    field = ""
    next
  }
  # Parse fields within a runner block
  in_runner && /^[[:space:]]+type:/ {
    sub(/^[[:space:]]+type:[[:space:]]*/, "")
    sub(/[[:space:]]*$/, "")
    rtype = $0; field = ""; next
  }
  in_runner && /^[[:space:]]+mode:/ {
    sub(/^[[:space:]]+mode:[[:space:]]*/, "")
    sub(/[[:space:]]*$/, "")
    mode = $0; field = ""; next
  }
  in_runner && /^[[:space:]]+preferred_selector:/ { field = "selector"; next }
  in_runner && /^[[:space:]]+best_for:/ { field = "best_for"; next }
  in_runner && /^[[:space:]]+avoid_for:/ { field = "avoid_for"; next }
  in_runner && /^[[:space:]]+notes:/ { field = "notes"; next }
  # New field key resets current field
  in_runner && /^[[:space:]]+[a-z_]+:/ { field = ""; next }
  # Parse array items
  in_runner && field != "" && /^[[:space:]]+-[[:space:]]/ {
    sub(/^[[:space:]]+-[[:space:]]+/, "")
    sub(/[[:space:]]*$/, "")
    val = $0
    if (field == "selector") { selectors[sel_count++] = val }
    else if (field == "best_for") { best_for[bf_count++] = val }
    else if (field == "avoid_for") { avoid_for[af_count++] = val }
    else if (field == "notes") { notes[note_count++] = val }
    next
  }
  END { flush_runner() }

  function flush_runner() {
    if (name == "") return
    sel_str = join_arr(selectors, sel_count)
    bf_str = join_arr(best_for, bf_count)
    af_str = join_arr(avoid_for, af_count)
    note_str = join_arr(notes, note_count)
    printf "%s|%s|%s|%s|%s|%s|%s\n", name, rtype, mode, sel_str, bf_str, af_str, note_str
    name = ""
    in_runner = 0
  }

  function join_arr(arr, count,    i, result) {
    result = ""
    for (i = 0; i < count; i++) {
      if (i > 0) result = result ","
      result = result arr[i]
    }
    return result
  }
  ' "$filepath"
}

# Extract routing rules from a YAML file
# Usage: rt_extract_rules "$filepath"
# Output: one rule per line
rt_extract_rules() {
  local filepath="$1"

  if [ ! -f "$filepath" ]; then
    return 1
  fi

  sed -n '/^routing_rules:/,/^[a-z]/{
    /^[[:space:]]*-[[:space:]]/{ s/^[[:space:]]*-[[:space:]]*//; s/[[:space:]]*$//; p; }
  }' "$filepath"
}

# Merge global and local runner targets, write cache files.
# Resolution: local runner definition wins entirely by name.
# routing_rules: local replaces global wholesale if present.
# Requires: bash 4.3+ (associative arrays + `local -n` namerefs in emit_runner_json)
#
# Usage: resolve_runner_targets
# Side effects (R38 — writes to the plugin-data cache dir from rt_cache_dir):
#   - Writes <rt_cache_dir>/routing-summary.txt
#   - Writes <rt_cache_dir>/runner-targets-merged.json
# Returns 0 on success, 1 if no config found (graceful degradation)
resolve_runner_targets() {
  # emit_runner_json() uses `local -n` namerefs, which require Bash 4.3+
  # (Feb 2014). The previous check accepted 4.0-4.2 and produced a
  # runtime error from the nameref declaration. Enforce 4.3 strictly.
  local _bv_major="${BASH_VERSINFO[0]:-0}"
  local _bv_minor="${BASH_VERSINFO[1]:-0}"
  if [ "$_bv_major" -lt 4 ] || { [ "$_bv_major" -eq 4 ] && [ "$_bv_minor" -lt 3 ]; }; then
    printf '[yellow-ci] Error: resolve_runner_targets requires Bash 4.3+. macOS users: install bash via Homebrew.\n' >&2
    return 1
  fi

  local global_path
  global_path=$(rt_global_path)
  local local_path
  local_path=$(rt_local_path)
  local cache_dir
  cache_dir=$(rt_cache_dir)
  local legacy_cache_dir
  legacy_cache_dir=$(rt_legacy_cache_dir)

  local has_global=0
  local has_local=0

  [ -f "$global_path" ] && has_global=1
  [ -f "$local_path" ] && has_local=1

  # Graceful degradation: no config
  if [ "$has_global" -eq 0 ] && [ "$has_local" -eq 0 ]; then
    # Clean up stale cache — both locations, so the legacy read-fallback
    # doesn't keep resurfacing deleted routing rules (R38).
    rm -f "${cache_dir}/routing-summary.txt" 2>/dev/null
    rm -f "${cache_dir}/runner-targets-merged.json" 2>/dev/null
    rm -f "${legacy_cache_dir}/routing-summary.txt" 2>/dev/null
    rm -f "${legacy_cache_dir}/runner-targets-merged.json" 2>/dev/null
    return 1
  fi

  # Validate available files
  if [ "$has_global" -eq 1 ] && ! validate_runner_targets_file "$global_path"; then
    printf '[yellow-ci] Warning: Global runner targets config is invalid, skipping\n' >&2
    has_global=0
  fi
  if [ "$has_local" -eq 1 ] && ! validate_runner_targets_file "$local_path"; then
    printf '[yellow-ci] Warning: Local runner targets config is invalid, skipping\n' >&2
    has_local=0
  fi

  if [ "$has_global" -eq 0 ] && [ "$has_local" -eq 0 ]; then
    # Clean up stale cache when no valid config remains — both locations, so
    # the legacy read-fallback doesn't keep resurfacing deleted routing rules
    # (R38).
    rm -f "${cache_dir}/routing-summary.txt" 2>/dev/null
    rm -f "${cache_dir}/runner-targets-merged.json" 2>/dev/null
    rm -f "${legacy_cache_dir}/routing-summary.txt" 2>/dev/null
    rm -f "${legacy_cache_dir}/runner-targets-merged.json" 2>/dev/null
    return 1
  fi

  # Ensure cache directory exists
  if ! mkdir -p "$cache_dir" 2>/dev/null; then
    printf '[yellow-ci] Warning: Cannot create cache directory %s\n' "$cache_dir" >&2
    return 1
  fi

  # Build merged runner list using associative array (local wins by name)
  declare -A merged_runners=()
  declare -a runner_order=()

  # Parse global first
  if [ "$has_global" -eq 1 ]; then
    while IFS= read -r line; do
      local rname="${line%%|*}"
      if [ -n "$rname" ]; then
        merged_runners["$rname"]="$line"
        runner_order+=("$rname")
      fi
    done < <(rt_extract_runners "$global_path")
  fi

  # Parse local — overwrites global entries by name, appends new ones
  if [ "$has_local" -eq 1 ]; then
    while IFS= read -r line; do
      local rname="${line%%|*}"
      if [ -n "$rname" ]; then
        if [ -z "${merged_runners[$rname]+x}" ]; then
          runner_order+=("$rname")
        fi
        merged_runners["$rname"]="$line"
      fi
    done < <(rt_extract_runners "$local_path")
  fi

  # Resolve routing rules: local replaces global wholesale if present
  local rules_source=""
  if [ "$has_local" -eq 1 ] && grep -qE '^routing_rules:' "$local_path"; then
    rules_source="$local_path"
  elif [ "$has_global" -eq 1 ] && grep -qE '^routing_rules:' "$global_path"; then
    rules_source="$global_path"
  fi

  local rule_count=0
  if [ -n "$rules_source" ]; then
    rule_count=$(rt_extract_rules "$rules_source" | wc -l | tr -d ' ')
  fi

  # Build routing summary (compact, under 300 chars)
  local pool_summary=""
  local pool_count=0
  local rdata rtype rmode_s bf_first mode_short entry
  for rname in "${runner_order[@]}"; do
    rdata="${merged_runners[$rname]}"
    rtype=$(printf '%s' "$rdata" | cut -d'|' -f2)
    rmode_s=$(printf '%s' "$rdata" | cut -d'|' -f3)
    bf_first=$(printf '%s' "$rdata" | cut -d'|' -f5 | cut -d',' -f1)

    mode_short=""
    case "$rmode_s" in
      jit_ephemeral) mode_short="jit" ;;
      persistent) mode_short="persist" ;;
      *) mode_short="$rmode_s" ;;
    esac

    entry="${rname} (${rtype}/${mode_short}"
    if [ -n "$bf_first" ]; then
      entry="${entry}, ${bf_first}"
    fi
    entry="${entry})"

    if [ -n "$pool_summary" ]; then
      pool_summary="${pool_summary}, ${entry}"
    else
      pool_summary="$entry"
    fi
    pool_count=$((pool_count + 1))
  done

  local summary="[yellow-ci] Runner pools: ${pool_summary}. ${rule_count} routing rule(s) loaded."

  # Truncate to 300 chars at word boundary if needed
  if [ ${#summary} -gt 300 ]; then
    summary="${summary:0:297}..."
  fi

  # Write routing summary (atomic write)
  rt_atomic_write "$summary" "${cache_dir}/routing-summary.txt"

  # Build and write merged JSON for agents (atomic write)
  local json
  json=$(emit_runner_json runner_order merged_runners "$rules_source" \
    "$has_global" "$has_local" "$global_path" "$local_path")
  rt_atomic_write "$json" "${cache_dir}/runner-targets-merged.json"

  return 0
}

# Helper: convert comma-separated string to JSON array
# Handles values containing spaces (e.g., "heavy CI,Terraform plan")
# Usage: csv_to_json_array "a,b,c" -> ["a","b","c"]
csv_to_json_array() {
  local csv="$1"
  if [ -z "$csv" ]; then
    printf '[]'
    return
  fi

  local result="["
  local first=1
  local item
  # Use parameter expansion to split on commas without word splitting on spaces
  local temp_csv="${csv},"
  while [ -n "$temp_csv" ]; do
    item="${temp_csv%%,*}"
    temp_csv="${temp_csv#*,}"
    # Skip empty trailing item from the appended comma
    if [ -z "$item" ] && [ -z "$temp_csv" ]; then
      break
    fi
    [ "$first" -eq 1 ] && first=0 || result="${result},"
    # Escape backslashes then double quotes for valid JSON
    item=$(printf '%s' "$item" | sed 's/\\/\\\\/g; s/"/\\"/g')
    result="${result}\"${item}\""
  done
  result="${result}]"
  printf '%s' "$result"
}
