#!/bin/bash
# resolve-runner-targets.sh — Config resolution, merge, and cache generation
# for runner targets configuration.
#
# Source this file: . "${SCRIPT_DIR}/lib/resolve-runner-targets.sh"
#
# Depends on: validate.sh (for validate_runner_targets_file, validate_runner_name)
#
# YAML parsing constraint: This parser handles only the canonical format
# generated by /ci:setup-runner-targets (2-space indent, block sequences only).
# Flow syntax ([a, b]), multi-line scalars (|, >), and tabs are NOT supported.
# If hand-edited YAML uses these features, the parser fails gracefully.

# Resolve the global config path (XDG-compliant)
# Usage: rt_global_path
rt_global_path() {
  printf '%s' "${XDG_CONFIG_HOME:-$HOME/.config}/yellow-ci/runner-targets.yaml"
}

# Resolve the local (per-repo) config path
# Usage: rt_local_path
rt_local_path() {
  printf '%s' ".claude/yellow-ci-runner-targets.yaml"
}

# Resolve the cache directory
# Usage: rt_cache_dir
rt_cache_dir() {
  printf '%s' "${HOME}/.cache/yellow-ci"
}

# Extract runner target blocks from a YAML file as JSON-like lines
# Each runner becomes: name|type|mode|selector1,selector2|best1,best2|avoid1,avoid2|note1,note2
# Usage: rt_extract_runners "$filepath"
# Output: one pipe-delimited line per runner target
rt_extract_runners() {
  local filepath="$1"

  if [ ! -f "$filepath" ]; then
    return 1
  fi

  awk '
  BEGIN { in_targets = 0; in_runner = 0; field = ""; name = ""; rtype = ""; mode = "" }
  # Detect runner_targets section
  /^runner_targets:/ { in_targets = 1; next }
  # Detect end of runner_targets section (new top-level key)
  in_targets && /^[a-z]/ { in_targets = 0; flush_runner() }
  # Detect new runner entry
  in_targets && /^[[:space:]]*-[[:space:]]+name:/ {
    flush_runner()
    in_runner = 1
    sub(/^[[:space:]]*-[[:space:]]+name:[[:space:]]*/, "")
    sub(/[[:space:]]*$/, "")
    name = $0
    rtype = ""; mode = ""
    delete selectors; sel_count = 0
    delete best_for; bf_count = 0
    delete avoid_for; af_count = 0
    delete notes; note_count = 0
    field = ""
    next
  }
  # Parse fields within a runner block
  in_runner && /^[[:space:]]+type:/ {
    sub(/^[[:space:]]+type:[[:space:]]*/, "")
    sub(/[[:space:]]*$/, "")
    rtype = $0; field = ""; next
  }
  in_runner && /^[[:space:]]+mode:/ {
    sub(/^[[:space:]]+mode:[[:space:]]*/, "")
    sub(/[[:space:]]*$/, "")
    mode = $0; field = ""; next
  }
  in_runner && /^[[:space:]]+preferred_selector:/ { field = "selector"; next }
  in_runner && /^[[:space:]]+best_for:/ { field = "best_for"; next }
  in_runner && /^[[:space:]]+avoid_for:/ { field = "avoid_for"; next }
  in_runner && /^[[:space:]]+notes:/ { field = "notes"; next }
  # New field key resets current field
  in_runner && /^[[:space:]]+[a-z_]+:/ { field = ""; next }
  # Parse array items
  in_runner && field != "" && /^[[:space:]]+-[[:space:]]/ {
    sub(/^[[:space:]]+-[[:space:]]+/, "")
    sub(/[[:space:]]*$/, "")
    val = $0
    if (field == "selector") { selectors[sel_count++] = val }
    else if (field == "best_for") { best_for[bf_count++] = val }
    else if (field == "avoid_for") { avoid_for[af_count++] = val }
    else if (field == "notes") { notes[note_count++] = val }
    next
  }
  END { flush_runner() }

  function flush_runner() {
    if (name == "") return
    sel_str = join_arr(selectors, sel_count)
    bf_str = join_arr(best_for, bf_count)
    af_str = join_arr(avoid_for, af_count)
    note_str = join_arr(notes, note_count)
    printf "%s|%s|%s|%s|%s|%s|%s\n", name, rtype, mode, sel_str, bf_str, af_str, note_str
    name = ""
    in_runner = 0
  }

  function join_arr(arr, count,    i, result) {
    result = ""
    for (i = 0; i < count; i++) {
      if (i > 0) result = result ","
      result = result arr[i]
    }
    return result
  }
  ' "$filepath"
}

# Extract routing rules from a YAML file
# Usage: rt_extract_rules "$filepath"
# Output: one rule per line
rt_extract_rules() {
  local filepath="$1"

  if [ ! -f "$filepath" ]; then
    return 1
  fi

  sed -n '/^routing_rules:/,/^[a-z]/{
    /^[[:space:]]*-[[:space:]]/{ s/^[[:space:]]*-[[:space:]]*//; s/[[:space:]]*$//; p; }
  }' "$filepath"
}

# Merge global and local runner targets, write cache files.
# Resolution: local runner definition wins entirely by name.
# routing_rules: local replaces global wholesale if present.
#
# Usage: resolve_runner_targets
# Side effects:
#   - Writes ~/.cache/yellow-ci/routing-summary.txt
#   - Writes ~/.cache/yellow-ci/runner-targets-merged.json
# Returns 0 on success, 1 if no config found (graceful degradation)
resolve_runner_targets() {
  local global_path
  global_path=$(rt_global_path)
  local local_path
  local_path=$(rt_local_path)
  local cache_dir
  cache_dir=$(rt_cache_dir)

  local has_global=0
  local has_local=0

  [ -f "$global_path" ] && has_global=1
  [ -f "$local_path" ] && has_local=1

  # Graceful degradation: no config
  if [ "$has_global" -eq 0 ] && [ "$has_local" -eq 0 ]; then
    # Clean up stale cache
    rm -f "${cache_dir}/routing-summary.txt" 2>/dev/null
    rm -f "${cache_dir}/runner-targets-merged.json" 2>/dev/null
    return 1
  fi

  # Validate available files
  if [ "$has_global" -eq 1 ] && ! validate_runner_targets_file "$global_path"; then
    printf '[yellow-ci] Warning: Global runner targets config is invalid, skipping\n' >&2
    has_global=0
  fi
  if [ "$has_local" -eq 1 ] && ! validate_runner_targets_file "$local_path"; then
    printf '[yellow-ci] Warning: Local runner targets config is invalid, skipping\n' >&2
    has_local=0
  fi

  if [ "$has_global" -eq 0 ] && [ "$has_local" -eq 0 ]; then
    return 1
  fi

  # Ensure cache directory exists
  if ! mkdir -p "$cache_dir" 2>/dev/null; then
    printf '[yellow-ci] Warning: Cannot create cache directory %s\n' "$cache_dir" >&2
    return 1
  fi

  # Build merged runner list using associative array (local wins by name)
  declare -A merged_runners=()
  declare -a runner_order=()

  # Parse global first
  if [ "$has_global" -eq 1 ]; then
    while IFS= read -r line; do
      local rname="${line%%|*}"
      if [ -n "$rname" ]; then
        merged_runners["$rname"]="$line"
        runner_order+=("$rname")
      fi
    done < <(rt_extract_runners "$global_path")
  fi

  # Parse local — overwrites global entries by name, appends new ones
  if [ "$has_local" -eq 1 ]; then
    while IFS= read -r line; do
      local rname="${line%%|*}"
      if [ -n "$rname" ]; then
        if [ -z "${merged_runners[$rname]+x}" ]; then
          runner_order+=("$rname")
        fi
        merged_runners["$rname"]="$line"
      fi
    done < <(rt_extract_runners "$local_path")
  fi

  # Resolve routing rules: local replaces global wholesale if present
  local rules_source=""
  if [ "$has_local" -eq 1 ] && grep -qE '^routing_rules:' "$local_path"; then
    rules_source="$local_path"
  elif [ "$has_global" -eq 1 ] && grep -qE '^routing_rules:' "$global_path"; then
    rules_source="$global_path"
  fi

  local rule_count=0
  if [ -n "$rules_source" ]; then
    rule_count=$(rt_extract_rules "$rules_source" | wc -l)
  fi

  # Build routing summary (compact, under 300 chars)
  local pool_summary=""
  local pool_count=0
  for rname in "${runner_order[@]}"; do
    local rdata="${merged_runners[$rname]}"
    local rtype mode bf_first
    rtype=$(printf '%s' "$rdata" | cut -d'|' -f2)
    mode=$(printf '%s' "$rdata" | cut -d'|' -f3)
    bf_first=$(printf '%s' "$rdata" | cut -d'|' -f5 | cut -d',' -f1)

    local mode_short=""
    case "$mode" in
      jit_ephemeral) mode_short="jit" ;;
      persistent) mode_short="persist" ;;
      *) mode_short="$mode" ;;
    esac

    local entry="${rname} (${rtype}/${mode_short}"
    if [ -n "$bf_first" ]; then
      entry="${entry}, ${bf_first}"
    fi
    entry="${entry})"

    if [ -n "$pool_summary" ]; then
      pool_summary="${pool_summary}, ${entry}"
    else
      pool_summary="$entry"
    fi
    pool_count=$((pool_count + 1))
  done

  local summary="[yellow-ci] Runner pools: ${pool_summary}. ${rule_count} routing rule(s) loaded."

  # Truncate to 300 chars at word boundary if needed
  if [ ${#summary} -gt 300 ]; then
    summary="${summary:0:297}..."
  fi

  # Write routing summary (atomic write)
  local tmp_summary="${cache_dir}/routing-summary.txt.tmp.$$"
  if printf '%s' "$summary" > "$tmp_summary" 2>/dev/null; then
    mv "$tmp_summary" "${cache_dir}/routing-summary.txt" 2>/dev/null || {
      printf '[yellow-ci] Warning: Cache write failed for routing-summary.txt\n' >&2
      rm -f "$tmp_summary" 2>/dev/null
    }
  fi

  # Build merged JSON for agents
  local json='{"schema":1,"runner_targets":['
  local first=1
  for rname in "${runner_order[@]}"; do
    local rdata="${merged_runners[$rname]}"
    local rtype mode selectors bf af nt
    rtype=$(printf '%s' "$rdata" | cut -d'|' -f2)
    mode=$(printf '%s' "$rdata" | cut -d'|' -f3)
    selectors=$(printf '%s' "$rdata" | cut -d'|' -f4)
    bf=$(printf '%s' "$rdata" | cut -d'|' -f5)
    af=$(printf '%s' "$rdata" | cut -d'|' -f6)
    nt=$(printf '%s' "$rdata" | cut -d'|' -f7)

    [ "$first" -eq 1 ] && first=0 || json="${json},"

    # Build JSON arrays from comma-separated values
    local sel_json=$(csv_to_json_array "$selectors")
    local bf_json=$(csv_to_json_array "$bf")
    local af_json=$(csv_to_json_array "$af")
    local nt_json=$(csv_to_json_array "$nt")

    json="${json}{\"name\":\"${rname}\",\"type\":\"${rtype}\",\"mode\":\"${mode}\""
    json="${json},\"preferred_selector\":${sel_json}"
    json="${json},\"best_for\":${bf_json}"
    json="${json},\"avoid_for\":${af_json}"
    json="${json},\"notes\":${nt_json}}"
  done
  json="${json}]"

  # Add routing rules
  if [ -n "$rules_source" ]; then
    json="${json},\"routing_rules\":["
    local rfirst=1
    while IFS= read -r rule; do
      [ "$rfirst" -eq 1 ] && rfirst=0 || json="${json},"
      # Escape double quotes in rule text
      rule=$(printf '%s' "$rule" | sed 's/"/\\"/g')
      json="${json}\"${rule}\""
    done < <(rt_extract_rules "$rules_source")
    json="${json}]"
  fi

  json="${json},"
  json="${json}\"_meta\":{\"global_path\":\"${global_path}\",\"local_path\":\"${local_path}\""
  json="${json},\"has_global\":${has_global},\"has_local\":${has_local}}}"

  # Write merged JSON (atomic write)
  local tmp_json="${cache_dir}/runner-targets-merged.json.tmp.$$"
  if printf '%s' "$json" > "$tmp_json" 2>/dev/null; then
    mv "$tmp_json" "${cache_dir}/runner-targets-merged.json" 2>/dev/null || {
      printf '[yellow-ci] Warning: Cache write failed for runner-targets-merged.json\n' >&2
      rm -f "$tmp_json" 2>/dev/null
    }
  fi

  return 0
}

# Helper: convert comma-separated string to JSON array
# Usage: csv_to_json_array "a,b,c" -> ["a","b","c"]
csv_to_json_array() {
  local csv="$1"
  if [ -z "$csv" ]; then
    printf '[]'
    return
  fi

  local result="["
  local first=1
  local IFS=','
  for item in $csv; do
    [ "$first" -eq 1 ] && first=0 || result="${result},"
    # Escape double quotes
    item=$(printf '%s' "$item" | sed 's/"/\\"/g')
    result="${result}\"${item}\""
  done
  result="${result}]"
  printf '%s' "$result"
}
