/**
 * @yellow-plugins/cli - Help Documentation Generator
 *
 * Generates Markdown help documentation from command metadata.
 * Ensures help docs stay synchronized with command definitions.
 *
 * Part of Task I1.T4: CLI command manifest
 */

import { getCommandsByCategory } from '../commands/registry.js';
import type { CommandMetadata } from '../types/commands.js';

/**
 * Generate the help baseline Markdown documentation.
 */
export function generateHelpBaseline(): string {
  const sections: string[] = [];

  // Header
  sections.push('# Yellow Plugins CLI - Command Reference');
  sections.push('');
  sections.push('> Auto-generated from command metadata. Do not edit manually.');
  sections.push('');
  sections.push('This document provides comprehensive help for all CLI commands in the Yellow Plugins marketplace.');
  sections.push('');
  sections.push('## Table of Contents');
  sections.push('');

  const categories = getCommandsByCategory();

  // Generate TOC
  for (const [categoryName, commands] of Object.entries(categories)) {
    const anchor = categoryName.toLowerCase().replace(/\s+/g, '-');
    sections.push(`- [${categoryName}](#${anchor})`);
    for (const cmd of commands) {
      if (cmd) {
        const cmdAnchor = cmd.name.toLowerCase().replace(/\s+/g, '-');
        sections.push(`  - [\`${cmd.name}\`](#${cmdAnchor})`);
      }
    }
  }

  sections.push('');
  sections.push('---');
  sections.push('');

  // Generate command details by category
  for (const [categoryName, commands] of Object.entries(categories)) {
    sections.push(`## ${categoryName}`);
    sections.push('');

    for (const cmd of commands) {
      if (cmd) {
        sections.push(...generateCommandSection(cmd));
      }
    }
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('## Global Options');
  sections.push('');
  sections.push('The following options are available for all commands:');
  sections.push('');
  sections.push('| Option | Description | Type | Alias |');
  sections.push('|--------|-------------|------|-------|');
  sections.push('| `--config` | Path to config file | string | - |');
  sections.push('| `--flags` | Path to feature flags file | string | - |');
  sections.push('| `--input` | Input file or data | string | `-i` |');
  sections.push('| `--output` | Output file or destination | string | `-o` |');
  sections.push('| `--verbose` | Enable verbose output | boolean | - |');
  sections.push('| `--dry-run` | Simulate without making changes | boolean | - |');
  sections.push('| `--help` | Show help | - | `-h` |');
  sections.push('| `--version` | Show version | - | `-v` |');
  sections.push('');

  sections.push('## Feature Flags');
  sections.push('');
  sections.push('Some commands require specific feature flags to be enabled. Configure these in `.claude-plugin/flags.json`:');
  sections.push('');
  sections.push('| Command | Required Flag | Description |');
  sections.push('|---------|---------------|-------------|');

  for (const [, commands] of Object.entries(categories)) {
    for (const cmd of commands) {
      if (cmd && cmd.requiredFlags && cmd.requiredFlags.length > 0) {
        for (const flag of cmd.requiredFlags) {
          sections.push(`| \`${cmd.name}\` | \`${flag}\` | Enable ${cmd.name} functionality |`);
        }
      }
    }
  }

  sections.push('');
  sections.push('## Error Codes');
  sections.push('');
  sections.push('Commands may emit structured error codes for troubleshooting:');
  sections.push('');
  sections.push('| Command | Error Codes | Description |');
  sections.push('|---------|-------------|-------------|');

  for (const [, commands] of Object.entries(categories)) {
    for (const cmd of commands) {
      if (cmd && cmd.errorCodes && cmd.errorCodes.length > 0) {
        sections.push(`| \`${cmd.name}\` | ${cmd.errorCodes.map(c => `\`${c}\``).join(', ')} | See specification for details |`);
      }
    }
  }

  sections.push('');
  sections.push('## Specification References');
  sections.push('');
  sections.push('Commands reference specific sections of the technical specification:');
  sections.push('');
  sections.push('| Command | Spec Anchors |');
  sections.push('|---------|--------------|');

  for (const [, commands] of Object.entries(categories)) {
    for (const cmd of commands) {
      if (cmd && cmd.specAnchors && cmd.specAnchors.length > 0) {
        sections.push(`| \`${cmd.name}\` | ${cmd.specAnchors.map(a => `\`${a}\``).join(', ')} |`);
      }
    }
  }

  sections.push('');
  sections.push('---');
  sections.push('');
  sections.push('*Generated by Yellow Plugins CLI*');
  sections.push('');

  return sections.join('\n');
}

/**
 * Generate a command section for the help documentation.
 */
function generateCommandSection(cmd: CommandMetadata): string[] {
  const lines: string[] = [];

  // Command header
  lines.push(`### \`${cmd.name}\``);
  lines.push('');

  // Aliases
  if (cmd.aliases && cmd.aliases.length > 0) {
    lines.push(`**Aliases:** ${cmd.aliases.map(a => `\`${a}\``).join(', ')}`);
    lines.push('');
  }

  // Description
  lines.push(cmd.description);
  lines.push('');

  // Usage
  if (cmd.usage) {
    lines.push('**Usage:**');
    lines.push('');
    lines.push('```bash');
    lines.push(cmd.usage);
    lines.push('```');
    lines.push('');
  }

  // Feature flags
  if (cmd.requiredFlags && cmd.requiredFlags.length > 0) {
    lines.push('**Required Feature Flags:**');
    lines.push('');
    for (const flag of cmd.requiredFlags) {
      lines.push(`- \`${flag}\``);
    }
    lines.push('');
  }

  // Examples
  if (cmd.examples && cmd.examples.length > 0) {
    lines.push('**Examples:**');
    lines.push('');
    for (const example of cmd.examples) {
      lines.push('```bash');
      lines.push(example.command);
      lines.push('```');
      lines.push('');
      lines.push(example.description);
      lines.push('');
    }
  }

  // Spec anchors
  if (cmd.specAnchors && cmd.specAnchors.length > 0) {
    lines.push('**Specification References:** ' + cmd.specAnchors.map(a => `\`${a}\``).join(', '));
    lines.push('');
  }

  // Error codes
  if (cmd.errorCodes && cmd.errorCodes.length > 0) {
    lines.push('**Error Codes:** ' + cmd.errorCodes.map(c => `\`${c}\``).join(', '));
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  return lines;
}
