#!/usr/bin/env python3
"""Yellow Plugins Statusline — generated by /statusline:setup
Re-run /statusline:setup after installing or removing plugins."""
import json, sys, os, subprocess, time, traceback

# --- Config (baked in by /statusline:setup) ---
STATUSLINE_VERSION = "1.0.0"
GENERATED_AT = "REPLACE_WITH_ISO_TIMESTAMP"
DETECTED_PLUGINS = REPLACE_WITH_DETECTED_PLUGINS
ENV_REQUIREMENTS = REPLACE_WITH_ENV_REQUIREMENTS
RUVECTOR_CHECK = REPLACE_WITH_BOOLEAN  # True if yellow-ruvector is installed
CONTEXT_WARN = 70
CONTEXT_CRIT = 90
GIT_CACHE_TTL = 5
CACHE_DIR = os.path.expanduser("~/.claude")

# --- Color helpers ---
USE_COLOR = (
    os.environ.get("NO_COLOR") is None
    and os.environ.get("TERM") != "dumb"
)

def c(code, text):
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text

# --- Cache helpers ---
def read_cache(path, ttl):
    try:
        if time.time() - os.path.getmtime(path) < ttl:
            return open(path).read()
    except (OSError, ValueError):
        pass
    return None

def write_cache(path, content):
    try:
        with open(path, "w") as f:
            f.write(content)
    except OSError:
        pass

# --- Segment functions ---
# Each returns (text, alert_level) or (text, alert_level, alert_details_list).
# alert_level: 0=normal, 1=warning, 2=critical.
# If text is None, the segment is skipped.

def segment_model(data):
    name = data.get("model", {}).get("display_name", "?")
    return (c("36", f"[{name}]"), 0)

def segment_context(data):
    pct = data.get("context_window", {}).get("used_percentage")
    if pct is None:
        return ("ctx:--", 0)
    pct = max(0, min(int(pct), 100))  # Clamp to 0-100
    bar_w = 10
    filled = pct * bar_w // 100
    bar = "\u2588" * filled + "\u2591" * (bar_w - filled)
    if pct >= CONTEXT_CRIT:
        return (c("31", f"{bar} {pct}%"), 2, [f"ctx: {pct}% (critical)"])
    elif pct >= CONTEXT_WARN:
        return (c("33", f"{bar} {pct}%"), 1, [f"ctx: {pct}% (warning)"])
    return (c("32", f"{bar} {pct}%"), 0)

def segment_git(data):
    cache_path = os.path.join(CACHE_DIR, "yellow-sl-git")
    cached = read_cache(cache_path, GIT_CACHE_TTL)
    if cached:
        parts = cached.split("\n")
        if len(parts) == 3:
            try:
                branch, staged, modified = parts[0], int(parts[1]), int(parts[2])
            except ValueError:
                return ("git:--", 0)
        else:
            return ("git:--", 0)
    else:
        try:
            git_cwd = data.get("cwd")
            branch = subprocess.check_output(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                stderr=subprocess.DEVNULL, timeout=2, cwd=git_cwd
            ).decode().strip()
            status = subprocess.check_output(
                ["git", "status", "--porcelain"],
                stderr=subprocess.DEVNULL, timeout=2, cwd=git_cwd
            ).decode()
            lines = [l for l in status.splitlines() if l]
            staged = sum(1 for l in lines if l[0] in "MADRC")
            modified = sum(1 for l in lines if len(l) > 1 and l[1] in "MD")
            write_cache(cache_path, f"{branch}\n{staged}\n{modified}")
        except Exception:
            return ("git:--", 0)
    dirty = staged + modified
    if dirty:
        info = []
        if staged:
            info.append(f"+{staged}")
        if modified:
            info.append(f"~{modified}")
        detail_parts = []
        if staged:
            detail_parts.append(f"{staged} staged")
        if modified:
            detail_parts.append(f"{modified} modified")
        return (c("33", f"{branch} {' '.join(info)}"), 1, [f"git: {', '.join(detail_parts)}"])
    return (c("36", branch), 0)

def segment_mcp_health(data):
    if not DETECTED_PLUGINS:
        return (None, 0)
    alerts = []
    summaries = []
    cwd = data.get("cwd", os.getcwd())
    for plugin, servers in sorted(DETECTED_PLUGINS.items()):
        short = plugin.replace("yellow-", "")
        ok = 0
        total = len(servers)
        for s in servers:
            envs = ENV_REQUIREMENTS.get(s)
            if s == "ruvector" and RUVECTOR_CHECK:
                # Special check: .ruvector/ directory in cwd
                if os.path.isdir(os.path.join(cwd, ".ruvector")):
                    ok += 1
                else:
                    alerts.append(f"ruvector: .ruvector/ missing (run /ruvector:setup)")
            elif envs is None or all(os.environ.get(e) for e in envs):
                ok += 1
            else:
                missing = [e for e in (envs or []) if not os.environ.get(e)]
                alerts.append(f"{s}: ${', $'.join(missing)} not set (run /{short}:setup)")
        if ok == total:
            summaries.append(c("32", f"{short}:OK"))
        else:
            summaries.append(c("33", f"{short}:{ok}/{total}"))
    text = " ".join(summaries)
    alert = 1 if alerts else 0
    return (text, alert, alerts if alerts else [])

def segment_agent(data):
    agent = data.get("agent", {})
    name = agent.get("name") if isinstance(agent, dict) else None
    if name:
        return (c("35", f"@{name}"), 0)
    return (None, 0)

def segment_duration(data):
    ms = data.get("cost", {}).get("total_duration_ms")
    if ms is None:
        return (None, 0)
    total_s = int(ms) // 1000
    minutes = total_s // 60
    seconds = total_s % 60
    if minutes < 1:
        return (f"{seconds}s", 0)
    return (f"{minutes}m {seconds}s", 0)

# --- Layout engine ---
def render():
    data = json.load(sys.stdin)
    segments = []
    alert_details = []
    max_alert = 0

    for fn in [segment_model, segment_context, segment_git,
               segment_mcp_health, segment_agent, segment_duration]:
        try:
            result = fn(data)
        except Exception:
            continue
        text, alert = result[0], result[1]
        if text is None:
            continue
        segments.append(text)
        max_alert = max(max_alert, alert)
        if len(result) > 2 and result[2]:
            alert_details.extend(result[2])

    line1 = " | ".join(segments)
    print(line1)

    if max_alert > 0 and alert_details:
        color = "31" if max_alert >= 2 else "33"
        print(c(color, " | ".join(alert_details)))

if __name__ == "__main__":
    try:
        render()
    except BrokenPipeError:
        pass  # Claude Code cancelled mid-output
    except Exception:
        try:
            with open(os.path.join(CACHE_DIR, "yellow-sl-error.log"), "a") as f:
                f.write(traceback.format_exc())
        except Exception:
            pass  # Never crash — blank statusline is better than error
